### ISSUE TITLE
Don't generate TypeScript definitions for classes imported with `@use`

### ISSUE THREAD

**Issue by simensol** [skovy/typed-scss-modules#210]
I'm using the Vuetify library which ships with a lot of utility classes. I'm `@extend` some of these classes in my own classes, e.g.:

```scss
@use "vuetify/styles";

.my-text-class {
    // Extend Vuetify's .text-wrap class:
    @extend .text-wrap;

    hyphens: none;
}
```

When I generate TypeScript definitions for this SCSS module, it also generate types for all the 4000+ Vuetify classes imported with `@use "vuetify/styles"`:

```typescript
export type Styles = {
  align_baseline: string;
  align_center: string;
  align_content_center: string;
  align_content_end: string;
  align_content_lg_center: string;
  align_content_lg_end: string;
  align_content_lg_space_around: string;
  ...
  my_text_class: string;
  ...
  w_100: string;
  w_25: string;
  w_33: string;
  w_50: string;
  w_66: string;
  w_75: string;
  w_auto: string;
};

export type ClassName = keyof Styles;

declare const styles: Styles;

export default styles;
```

Is there a way to make `typed-scss-modules` generate TypeScript definitions for my own classes only?
