### ISSUE TITLE
--watch should also re-build dependants

### ISSUE THREAD

**Issue by burtek** [skovy/typed-scss-modules#46]
```scss
// _variables.scss
$colors: (
    red: #FF0000,
    green: #00FF00
);
```
```scss
// index.scss
@import './variables';
@each $name, $color in $colors {
    .text--#{$name} {
        color: $color
    }
}
```

`tsm --watch --exportType default` correctly generates `index.scss.d.ts` with `textRed` and `textGreen`, but when I add/remove color from `_variables.scss` while running `--watch`, `index.scss.d.ts` won't be rebuilt until I re-save `index.scss`.

<hr />

Similarly, consider following file:

```scss
// types.scss
@import './variables';
:export {
    @each $name, $color in $colors {
        #{$name}: $color;
    }
}
```

```ts
// types.ts
import { Styles as Colors } from './types.scss';

export type Color = keyof Colors;
```

With `tsm --watch --exportType default` `type Color` won't get updated until I re-save `types.scss`. I believe this to be the exact same case as above.
